import 'package:todoapp/src/features/home/domain/entities/todo_model.dart';

List<ToDoModel> demoData = [
  ToDoModel(
    id: '1',
    title: 'Task 1',
    description: 'Description for Task 1',
    createdAt: '2024-04-20',
    isDone: false,
  ),
  ToDoModel(
    id: '2',
    title: 'Task 2',
    description: 'Description for Task 2',
    createdAt: '2024-04-21',
    isDone: false,
  ),
  ToDoModel(
    id: '3',
    title: 'Task 3',
    description: 'Description for Task 3',
    createdAt: '2024-04-22',
    isDone: true,
    completedAt: '2024-04-23',
  ),
  ToDoModel(
    id: '4',
    title: 'Task 4',
    description: 'Description for Task 4',
    createdAt: '2024-04-24',
    isDone: false,
  ),
  ToDoModel(
    id: '5',
    title: 'Task 5',
    description: 'Description for Task 5',
    createdAt: '2024-04-25',
    isDone: true,
    completedAt: '2024-04-26',
  ),
  ToDoModel(
    id: '6',
    title: 'Task 6',
    description: 'Description for Task 6',
    createdAt: '2024-04-27',
    isDone: false,
  ),
  ToDoModel(
    id: '7',
    title: 'Task 7',
    description: 'Description for Task 7',
    createdAt: '2024-04-28',
    isDone: false,
  ),
  ToDoModel(
    id: '8',
    title: 'Task 8',
    description: 'Description for Task 8',
    createdAt: '2024-04-29',
    isDone: true,
    completedAt: '2024-04-30',
  ),
  ToDoModel(
    id: '9',
    title: 'Task 9',
    description: 'Description for Task 9',
    createdAt: '2024-05-01',
    isDone: false,
  ),
  ToDoModel(
    id: '10',
    title: 'Task 10',
    description: 'Description for Task 10',
    createdAt: '2024-05-02',
    isDone: true,
    completedAt: '2024-05-03',
  ),
];
